name: just_motion
description: Create organic motion transitions in a reactive way using basic easing in Flutter.
version: 0.0.5+15
homepage: https://roipeker.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
